### ISSUE TITLE
Kreiranje i uredjivanje Home stranice

### ISSUE THREAD

**Issue by RadonicA** [codeandrelax/2DSpaceMapping_A#10]
Home stranica , izmedju ostalog, podrazumijeva i README.md fajl  gdje se vrši definisanje zahjeva projektnog zadatka.
Neophodno je održavati postojeći i kreirati novi sadržaj, koji je dostupan za javnost.

**Comment by RadonicA** [comment]
Težina zadatka : 5

**Comment by RadonicA** [comment]
Procijenjeno vrijeme izrade: 10 h

**Comment by lukavidic** [comment]
Težina zadatka: 6

**Comment by Neira7** [comment]
Tezina zadatka: 6

**Comment by RadonicA** [comment]
Utroseno vrijeme izrade: 10h
