### ISSUE TITLE
Implementacija wireless komunikacije

### ISSUE THREAD

**Issue by RadonicA** [codeandrelax/2DSpaceMapping_A#12]
Implementirati odgovarajuću infrastrukturu koja obezbjeđuje WiFI komunikaciju softvera na PC i WiFI modula sa strane mikrokontrolera.

**Comment by lukavidic** [comment]
Težina zadatka: 5

**Comment by RadonicA** [comment]
Tezina zadatka: 5

**Comment by Neira7** [comment]
Tezina zadatka: 5

**Comment by Neira7** [comment]
Procijenjeno vrijeme izrade: 2h

**Comment by Neira7** [comment]
Utroseno vrijeme rada: 2h30m
