### ISSUE TITLE
Implementirati algoritam iscrtavanja

### ISSUE THREAD

**Issue by RadonicA** [codeandrelax/2DSpaceMapping_A#14]
Implementirati algoritam iscrtavanja informacija o udaljenosti objekata koji se dobijaju od strane LIDAR-a preko WiFi komunikacije.

**Comment by lukavidic** [comment]
Težina zadatka: 7

**Comment by RadonicA** [comment]
Tezina zadatka: 8

**Comment by Neira7** [comment]
Tezina zadatka: 8

**Comment by Neira7** [comment]
Procijenjeno vrijeme izrade: 5h

**Comment by Neira7** [comment]
Utroseno vrijeme rada: 6h
