### ISSUE TITLE
Implementirati upravljanje kretanja kroz aplikaciju

### ISSUE THREAD

**Issue by RadonicA** [codeandrelax/2DSpaceMapping_A#15]
Obezbjediti GUI podršku za zahtjevane funkcionalnosti kretanja (zaustavljanje i pokretanje) i osmisliti način proslijeđivanja datih poruka ka mikrokontroleru putem WiFI komunikacije.

**Comment by lukavidic** [comment]
Težina zadatka: 6

**Comment by RadonicA** [comment]
Težina zadatka: 7

**Comment by lukavidic** [comment]
Procjenjeno vrijeme izrade: ~3h

**Comment by Neira7** [comment]
Tezina zadatka: 6

**Comment by lukavidic** [comment]
Utrošeno vrijeme za izradu: ~3h
