### ISSUE TITLE
Provjeriti mogućnosti implementacije simulatora LIDAR-a

### ISSUE THREAD

**Issue by RadonicA** [codeandrelax/2DSpaceMapping_A#16]
Provjeriti da li postoje alati za simulaciju generisanja podataka sličnih kao onih sa LIDAR-a i pokušati integraciju istog sa aplikacijom za iscrtavanje.

**Comment by lukavidic** [comment]
Težina zadatka: 8

**Comment by RadonicA** [comment]
Tezina zadatka: 9

**Comment by lukavidic** [comment]
Procjenjeno vrijeme izrade: ~10h

**Comment by Neira7** [comment]
Tezina zadatka: 7

**Comment by lukavidic** [comment]
Utrošeno vrijeme rada: ~8h
