### ISSUE TITLE
Proučiti način komunikacije sa WiFi modulom

### ISSUE THREAD

**Issue by RadonicA** [codeandrelax/2DSpaceMapping_A#17]
Dokumentovati princip rada iskorišćenog WiFi modula i način komunikacije u smislu softverske implementacije i načina slanja i primanja poruka. Dokumentovati detaljnije na Wiki stranici.

**Comment by lukavidic** [comment]
Težina zadatka: 9

**Comment by RadonicA** [comment]
Težina zadatka: 9

**Comment by lukavidic** [comment]
Procjenjeno vrijeme izrade: ~3h

**Comment by Neira7** [comment]
Tezina zadatka: 9

**Comment by Neira7** [comment]
Procijenjeno vrijeme izrade: 10h

**Comment by Neira7** [comment]
Utrošeno vrijeme izrade: ~15h
