### ISSUE TITLE
Provjera lemova i kontakata na štampanoj pločici

### ISSUE THREAD

**Issue by lukavidic** [codeandrelax/2DSpaceMapping_A#19]
Provjeriti da li su sve komponente zalemljene kako treba i provjeriti da li postoje nepoželjni kratki spojevi.

**Comment by lukavidic** [comment]
Težina zadatka: 5

**Comment by RadonicA** [comment]
Težina zadatka: 5

**Comment by RadonicA** [comment]
Procijenjeno vrijeme izrade: 30min

**Comment by RadonicA** [comment]
Utroseno vrijeme: 30min

**Comment by Neira7** [comment]
Tezina zadatka: 5
