### ISSUE TITLE
Testiranje i programiranje stampane ploče pomoću programatora

### ISSUE THREAD

**Issue by RadonicA** [codeandrelax/2DSpaceMapping_A#20]
Napisati testni program za provjeru ispravnosti štampane ploče.

**Comment by RadonicA** [comment]
Procijenjeno vrijeme: 2h

**Comment by RadonicA** [comment]
Tezina zadatka : 6

**Comment by RadonicA** [comment]
![Image](https://github.com/codeandrelax/2DSpaceMapping_A/assets/127949851/c37d80f9-fbc3-42ae-954b-47f53d3ece86)

**Comment by lukavidic** [comment]
Težina zadatka: 5

**Comment by RadonicA** [comment]
Utroseno vrijeme: 2h

**Comment by Neira7** [comment]
Tezina zadatka: 5
