### ISSUE TITLE
Upoznavanje sa IR distance click senzorom

### ISSUE THREAD

**Issue by RadonicA** [codeandrelax/2DSpaceMapping_A#21]
Napisati wiki stranicu o IR distance click senzoru. Detaljnije se upoznati sa funkcionalnostima senzora i nacinu povezivanja sa mikrokontrolerom.

**Comment by Neira7** [comment]
Tezina zadatka: 5

**Comment by lukavidic** [comment]
Težina zadatka: 5

**Comment by RadonicA** [comment]
Težina zadatka: 5

**Comment by RadonicA** [comment]
Procijenjeno vrijeme izrade: 2h

**Comment by RadonicA** [comment]
Vrijeme izrade: 1h
