### ISSUE TITLE
Osposobljavanje IR distance click senzora

### ISSUE THREAD

**Issue by RadonicA** [codeandrelax/2DSpaceMapping_A#22]
Napisati kod koji testira funckionalost IR distance click senzora

**Comment by Neira7** [comment]
Tezina zadatka: 6

**Comment by lukavidic** [comment]
Težina zadatka: 6

**Comment by RadonicA** [comment]
Težina zadatka: 6

**Comment by RadonicA** [comment]
Procijenjeno vrijeme izrade: 3h
