### ISSUE TITLE
Upoznavanje sa servo motorom

### ISSUE THREAD

**Issue by RadonicA** [codeandrelax/2DSpaceMapping_A#23]
Upoznati se sa karakteristikama i funkcijama samog servo motora. Napraviti wiki stranicu sa detaljnijim opisom.

**Comment by Neira7** [comment]
Tezina zadatka: 5

**Comment by lukavidic** [comment]
Težina zadatka: 3

**Comment by lukavidic** [comment]
Procjenjeno vrijeme izrade: 3h

**Comment by RadonicA** [comment]
Težina zadatka: 3

**Comment by lukavidic** [comment]
Utrošeno vrijeme za izradu: ~10h

**Comment by lukavidic** [comment]
Utrošeno vrijeme izrade: ~3h
