### ISSUE TITLE
Osposobljavanje servo motora

### ISSUE THREAD

**Issue by RadonicA** [codeandrelax/2DSpaceMapping_A#24]
Napisati testni kod za rad sa servo motorom.

**Comment by Neira7** [comment]
Tezina zadatka: 6

**Comment by lukavidic** [comment]
Težina zadatka: 5

**Comment by lukavidic** [comment]
Procjenjeno vrijeme izrade: 3h

**Comment by RadonicA** [comment]
Težina zadatka: 5

**Comment by lukavidic** [comment]
Utrošeno vrijeme za izradu: ~10h
