### ISSUE TITLE
Implementacija WiFi komunikacije

### ISSUE THREAD

**Issue by RadonicA** [codeandrelax/2DSpaceMapping_A#25]
Napisati firmware kod za testiranje rada WiFi modula.

**Comment by Neira7** [comment]
Tezina zadatka: 8

**Comment by Neira7** [comment]
Procijenjeno vrijeme izrade: 6h

**Comment by lukavidic** [comment]
Težina zadatka: 8

**Comment by RadonicA** [comment]
Težina zadatka: 8

**Comment by lukavidic** [comment]
Utrošeno vrijeme za izradu: >50h
