### ISSUE TITLE
Osposobljavanje komunikacije sa postojećom pločom

### ISSUE THREAD

**Issue by RadonicA** [codeandrelax/2DSpaceMapping_A#26]
Napisati kod koji omogucava pokretanje motora i komunikaciju sa postojecom plocom. Dokumentovati testirani primjer na Wiki stranici.

**Comment by lukavidic** [comment]
Težina zadatka: 6

**Comment by RadonicA** [comment]
Težina zadatka: 5

**Comment by Neira7** [comment]
Tezina zadatka: 6

**Comment by RadonicA** [comment]
Procijenjeno vrijeme izrade: 10h

**Comment by RadonicA** [comment]
Utroseno vrijeme izrade: 15h
