### ISSUE TITLE
Integracija servo motora i IR senzora

### ISSUE THREAD

**Issue by lukavidic** [codeandrelax/2DSpaceMapping_A#27]
Napisati firmware program koji integriše funkcionalnosti servo motora i IR senzora tako da se dobije radar koji će da skenira okruženja autonomnog vozila.

**Comment by lukavidic** [comment]
Procjenjeno vrijeme rada: 2h

**Comment by lukavidic** [comment]
Težina zadatka: 7

**Comment by RadonicA** [comment]
Težina zadatka: 7

**Comment by Neira7** [comment]
Težina zadatka: 7

**Comment by lukavidic** [comment]
Utrošeno vrijeme za izradu: ~20h
