### ISSUE TITLE
Modifikacija aplikacije za mapiranje prostora

### ISSUE THREAD

**Issue by lukavidic** [codeandrelax/2DSpaceMapping_A#28]
Modifikovati aplikaciju za mapiranje prostora tako da se prilagodi podacima koji se šalju sa autonomnog vozila, ali i da se zadrži mogućnost upotrebe simulatora.

**Comment by lukavidic** [comment]
Težina zadatka: 5

**Comment by lukavidic** [comment]
Procjena vremena izrade: 1h

**Comment by Neira7** [comment]
Težina zadatka: 5

**Comment by RadonicA** [comment]
Težina zadatka: 5

**Comment by lukavidic** [comment]
Utrošeno vrijeme za izradu: 30 min.
