### ISSUE TITLE
Sklapanje autonomnog vozila

### ISSUE THREAD

**Issue by RadonicA** [codeandrelax/2DSpaceMapping_A#29]
Sklopiti i povezati dobijene dijelove vozila i postaviti prateće komponente na vozilo.Postaviti na Home stranicu sliku sklopljenog vozila.

**Comment by RadonicA** [comment]
Procijenjeno vrijeme: 1 h

**Comment by lukavidic** [comment]
Težina zadatka: 3

**Comment by RadonicA** [comment]
Tezina zadatka: 3

**Comment by Neira7** [comment]
Tezina zadatka: 3

**Comment by RadonicA** [comment]
Vrijeme izrade: 1h
