### ISSUE TITLE
Odabir komponenata štampane ploče

### ISSUE THREAD

**Issue by RadonicA** [codeandrelax/2DSpaceMapping_A#3]
Proučavanje komponenata neophodnih za projektovanje štampane ploče.
Rezultat zadatka jeste wiki stranica sa potrebnom dokumentacijom.

**Comment by lukavidic** [comment]
Težina zadatka: 5

**Comment by RadonicA** [comment]
Težina zadatka: 6

**Comment by Neira7** [comment]
Težina zadatka: 5

**Comment by RadonicA** [comment]
Procijenjeno vrijeme izrade: 3h

**Comment by RadonicA** [comment]
Utrošeno vrijeme : 7h
