### ISSUE TITLE
Integracija i osposobljavanje sistema

### ISSUE THREAD

**Issue by RadonicA** [codeandrelax/2DSpaceMapping_A#30]
Napisati kod koji integriše sve komponente u jeda  kod i omogućava osposobljavanje cijelog sistema.
Napraviti Wiki stranicu koja dokumentuje funkcionalnost.

**Comment by lukavidic** [comment]
Težina zadatka: 8

**Comment by lukavidic** [comment]
Procjenjeno vrijeme izrade: 10h

**Comment by RadonicA** [comment]
Tezina zadatka:9

**Comment by Neira7** [comment]
Tezina zadatka: 9

**Comment by lukavidic** [comment]
Utrošeno vrijeme za izradu: ~30h
