### ISSUE TITLE
Modifikacija softverskih aplikacija

### ISSUE THREAD

**Issue by lukavidic** [codeandrelax/2DSpaceMapping_A#31]
Zbog izmjenjenih zahtjeva i kompatibilnosti sa radom WiFi modula ESP8266-01 potrebno je razdvojiti aplikacije za simulator i za rad sa stvarnim autonomnim vozilom.

**Comment by lukavidic** [comment]
Procjenjeno vrijeme rada: 4h

**Comment by lukavidic** [comment]
Težina zadatka: 5

**Comment by RadonicA** [comment]
Težina zadatka: 5

**Comment by Neira7** [comment]
Tezina zadatka: 5

**Comment by lukavidic** [comment]
Utrošeno vrijeme za izradu: ~4h
