### ISSUE TITLE
Upoznavanje sa ultrazvučnim senzorom

### ISSUE THREAD

**Issue by RadonicA** [codeandrelax/2DSpaceMapping_A#32]
Upoznavanje sa HC-SR04 ultrazvučnim senzorom i ispitivanje njegovih funkcionalnosti. Dokumentaciju priložiti u vidu Wiki stranice.

**Comment by RadonicA** [comment]
Procijenjeno vrijeme izrade: 2h

**Comment by RadonicA** [comment]
Tezina zadatka: 6

**Comment by lukavidic** [comment]
Težina zadatka: 5

**Comment by Neira7** [comment]
Tezina zadatka: 6

**Comment by RadonicA** [comment]
Utrošeno vijeme: ~1h
