### ISSUE TITLE
Projektovanje električne šeme

### ISSUE THREAD

**Issue by RadonicA** [codeandrelax/2DSpaceMapping_A#4]
Zadatak je osmisliti dizajn električne šeme i rezultat je wiki stranica gdje je dokumentovan princip dizajniranja šeme.
Odrediti fizičke karakteristike štampane pločice.

**Comment by RadonicA** [comment]
Težina zadatka: 9

**Comment by lukavidic** [comment]
Težina zadatka: 9

**Comment by Neira7** [comment]
Težina zadatka: 9

**Comment by RadonicA** [comment]
Procijenjeno vrijeme izrade: 13h

**Comment by lukavidic** [comment]
Utrošeno vrijeme: ~20h
