### ISSUE TITLE
Ispitivanje funkcionalnosti postojeće štampane ploče

### ISSUE THREAD

**Issue by RadonicA** [codeandrelax/2DSpaceMapping_A#5]
Upoznavanje sa karakteristikama i funkcionalnostima ploče autonomnog vozila. Posebno obratiti pažnju i opisati način komunikacije sa pločom sa strane mikrokontrolera. Rezultat izvršavanja zadatka je wiki stranica u kojoj se nalaze dokumentovani prethodno opisani zahtjevi zadatka.

**Comment by lukavidic** [comment]
Težina zadatka: 5

**Comment by RadonicA** [comment]
Težina zadatka: 6

**Comment by Neira7** [comment]
Težina zadatka: 6

**Comment by Neira7** [comment]
Utrošeno vrijeme: 4h
