### ISSUE TITLE
Sastavljanje liste komponenata i pitanja za Project owner-a

### ISSUE THREAD

**Issue by lukavidic** [codeandrelax/2DSpaceMapping_A#6]
Zadatak je prikupljanje svih web linkova sa sajta kataloga koji vode ka komponentama koje je potrebno naručiti. Pored navedenog potrebno je i sastaviti spisak pitanja za Project owner-a u svrhu mogućnosti nastavljanja rada na projektu. Rezultat izvršavanja zadatka su dva fajla na repozitorijumu koja sadrže prethodno navedeno.

**Comment by lukavidic** [comment]
Težina zadatka: 3

**Comment by Neira7** [comment]
Težina zadatka: 3

**Comment by RadonicA** [comment]
Težina zadatka : 3

**Comment by Neira7** [comment]
Utrošeno vrijeme: 2h30m
