### ISSUE TITLE
Raspored komponenata na PCB

### ISSUE THREAD

**Issue by Neira7** [codeandrelax/2DSpaceMapping_A#7]
Zadatak je započeti projektovanje štampane ploče. Obratiti pažnju na zahtijevane karakteristike same ploče. Rasporediti komponente na način da se dobiju što bolje performanse.

**Comment by RadonicA** [comment]
Procijenjeno vrijeme izrade: 3h

**Comment by RadonicA** [comment]
Težina zadatka : 8

**Comment by lukavidic** [comment]
Težina zadatka 7

**Comment by RadonicA** [comment]
Utrošeno vrijeme : ~2h 30m
