### ISSUE TITLE
Rutiranje komponenata na PCB

### ISSUE THREAD

**Issue by Neira7** [codeandrelax/2DSpaceMapping_A#8]
Na odgovarajući način povezati komponente na štampanoj ploči. Rezultat ovog zadatka je projektovana štampana ploča.

**Comment by RadonicA** [comment]
Procijenjeno vrijeme izrade: 8h

**Comment by RadonicA** [comment]
Težina zadatka : 9

**Comment by lukavidic** [comment]
Težina zadatka: 9

**Comment by RadonicA** [comment]
Utrošeno vrijeme : 4h
