### ISSUE TITLE
Kreiranje simbola i modela za Edge Connector

### ISSUE THREAD

**Issue by lukavidic** [codeandrelax/2DSpaceMapping_A#9]
Zadatak je kreirati simbol i PCB layout komponente _Edge Connector_ u alatu KiCad koja je neophodna za komunikaciju mikrokontrolera sa postojećom štampanom pločom. Rezultat izvršavanja ovog zadatka je gotov model koji je iskorišćen u glavnoj šemi kao i wiki stranica koja opisuje _Edge Connector_.

**Comment by lukavidic** [comment]
Težina zadatka: 8

**Comment by Neira7** [comment]
Težina zadatka: 9

**Comment by RadonicA** [comment]
Težina zadatka : 9

**Comment by RadonicA** [comment]
Na ovaj zadatak utroseno je 3h 15m.

**Comment by RadonicA** [comment]
Procijenjeno vrijeme izrade: 6h

**Comment by lukavidic** [comment]
Utroseno vrijeme za izradu zadatka: ~ 6h 30min
